//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIESB.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instituicao
    {
        public Instituicao()
        {
            this.ProgramaPosGraduacao = new HashSet<ProgramaPosGraduacao>();
        }
    
        public int ID { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> ID_UF { get; set; }
    
        public virtual UF UF { get; set; }
        public virtual ICollection<ProgramaPosGraduacao> ProgramaPosGraduacao { get; set; }
    }
}
