//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIESB.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramaPosGraduacao
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public int ID_Instituicao { get; set; }
    
        public virtual Instituicao Instituicao { get; set; }
    }
}
