//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DIESBModel", "FK_Instituicao_0", "UF", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Importar.UF), "Instituicao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Importar.Instituicao), true)]
[assembly: EdmRelationshipAttribute("DIESBModel", "FK_ProgramaPosGraduacao_0", "Instituicao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Importar.Instituicao), "ProgramaPosGraduacao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Importar.ProgramaPosGraduacao), true)]

#endregion

namespace Importar
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DIESBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DIESBContext object using the connection string found in the 'DIESBContext' section of the application configuration file.
        /// </summary>
        public DIESBContext() : base("name=DIESBContext", "DIESBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DIESBContext object.
        /// </summary>
        public DIESBContext(string connectionString) : base(connectionString, "DIESBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DIESBContext object.
        /// </summary>
        public DIESBContext(EntityConnection connection) : base(connection, "DIESBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Instituicao> Instituicao
        {
            get
            {
                if ((_Instituicao == null))
                {
                    _Instituicao = base.CreateObjectSet<Instituicao>("Instituicao");
                }
                return _Instituicao;
            }
        }
        private ObjectSet<Instituicao> _Instituicao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProgramaPosGraduacao> ProgramaPosGraduacao
        {
            get
            {
                if ((_ProgramaPosGraduacao == null))
                {
                    _ProgramaPosGraduacao = base.CreateObjectSet<ProgramaPosGraduacao>("ProgramaPosGraduacao");
                }
                return _ProgramaPosGraduacao;
            }
        }
        private ObjectSet<ProgramaPosGraduacao> _ProgramaPosGraduacao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UF> UF
        {
            get
            {
                if ((_UF == null))
                {
                    _UF = base.CreateObjectSet<UF>("UF");
                }
                return _UF;
            }
        }
        private ObjectSet<UF> _UF;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Instituicao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInstituicao(Instituicao instituicao)
        {
            base.AddObject("Instituicao", instituicao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProgramaPosGraduacao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProgramaPosGraduacao(ProgramaPosGraduacao programaPosGraduacao)
        {
            base.AddObject("ProgramaPosGraduacao", programaPosGraduacao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UF EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUF(UF uF)
        {
            base.AddObject("UF", uF);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DIESBModel", Name="Instituicao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Instituicao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Instituicao object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Instituicao CreateInstituicao(global::System.Int32 id, global::System.String descricao)
        {
            Instituicao instituicao = new Instituicao();
            instituicao.ID = id;
            instituicao.Descricao = descricao;
            return instituicao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_UF
        {
            get
            {
                return _ID_UF;
            }
            set
            {
                OnID_UFChanging(value);
                ReportPropertyChanging("ID_UF");
                _ID_UF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_UF");
                OnID_UFChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_UF;
        partial void OnID_UFChanging(Nullable<global::System.Int32> value);
        partial void OnID_UFChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DIESBModel", "FK_Instituicao_0", "UF")]
        public UF UF
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UF>("DIESBModel.FK_Instituicao_0", "UF").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UF>("DIESBModel.FK_Instituicao_0", "UF").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UF> UFReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UF>("DIESBModel.FK_Instituicao_0", "UF");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UF>("DIESBModel.FK_Instituicao_0", "UF", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DIESBModel", "FK_ProgramaPosGraduacao_0", "ProgramaPosGraduacao")]
        public EntityCollection<ProgramaPosGraduacao> ProgramaPosGraduacao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProgramaPosGraduacao>("DIESBModel.FK_ProgramaPosGraduacao_0", "ProgramaPosGraduacao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProgramaPosGraduacao>("DIESBModel.FK_ProgramaPosGraduacao_0", "ProgramaPosGraduacao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DIESBModel", Name="ProgramaPosGraduacao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProgramaPosGraduacao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProgramaPosGraduacao object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="iD_Instituicao">Initial value of the ID_Instituicao property.</param>
        public static ProgramaPosGraduacao CreateProgramaPosGraduacao(global::System.Int32 id, global::System.String descricao, global::System.Int32 iD_Instituicao)
        {
            ProgramaPosGraduacao programaPosGraduacao = new ProgramaPosGraduacao();
            programaPosGraduacao.ID = id;
            programaPosGraduacao.Descricao = descricao;
            programaPosGraduacao.ID_Instituicao = iD_Instituicao;
            return programaPosGraduacao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Instituicao
        {
            get
            {
                return _ID_Instituicao;
            }
            set
            {
                OnID_InstituicaoChanging(value);
                ReportPropertyChanging("ID_Instituicao");
                _ID_Instituicao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Instituicao");
                OnID_InstituicaoChanged();
            }
        }
        private global::System.Int32 _ID_Instituicao;
        partial void OnID_InstituicaoChanging(global::System.Int32 value);
        partial void OnID_InstituicaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DIESBModel", "FK_ProgramaPosGraduacao_0", "Instituicao")]
        public Instituicao Instituicao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instituicao>("DIESBModel.FK_ProgramaPosGraduacao_0", "Instituicao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instituicao>("DIESBModel.FK_ProgramaPosGraduacao_0", "Instituicao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Instituicao> InstituicaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instituicao>("DIESBModel.FK_ProgramaPosGraduacao_0", "Instituicao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Instituicao>("DIESBModel.FK_ProgramaPosGraduacao_0", "Instituicao", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DIESBModel", Name="UF")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UF : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UF object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static UF CreateUF(global::System.Int32 id, global::System.String descricao)
        {
            UF uF = new UF();
            uF.ID = id;
            uF.Descricao = descricao;
            return uF;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DIESBModel", "FK_Instituicao_0", "Instituicao")]
        public EntityCollection<Instituicao> Instituicao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Instituicao>("DIESBModel.FK_Instituicao_0", "Instituicao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Instituicao>("DIESBModel.FK_Instituicao_0", "Instituicao", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
